# Site Settings
title:               new a Sky
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Lagrange"
url:                #"https://github.com/yangyang1009/Lagrange.git"
github:
  url:               #"https://github.com/yangyang1009/Lagrange"
author:
  name:              "Yang Ning"
  email:             "ningy1009@163.com"
  github:            "yangyang1009"
  linkedin:          "www.newasky.com"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
